# URL kết nối đến SQL Server (Sửa "ten_database_cua_ban" thành tên DB thực tế bạn đã tạo)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LibraryDB;encrypt=true;trustServerCertificate=true;

# Tài khoản và mật khẩu đăng nhập SQL Server của bạn (thường mặc định là sa)
spring.datasource.username=sa
spring.datasource.password=1

# Driver class cho SQL Server
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8085